name: Daily Commit

on:
  schedule:
    - cron: '0 6 * * *'  # каждый день в 06:00 UTC
  workflow_dispatch:     # запуск вручную

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update README.md
        run: |
          echo "✅ Автообновление: $(date -u)" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "vadimoroz41261@gmail.com"
          git add README.md
          git commit -m "📌 Автообновление: $(date -u)" || echo "No changes to commit"
          git push
